#! /bin/bash -eux

# delete templates
## deleted files
git diff --cached --name-only --diff-filter=D | grep "src/.*\.hpp$" | sed -e "s/src/templates/g" -e "s/hpp$/xml/g" | xargs rm -f
## renamed files
git diff --cached | grep "rename from src/.*\.hpp$" | sed -e "s/rename from //g" -e "s/src/templates/g" -e "s/hpp$/xml/g" | xargs rm -f

# generate templates
find src/*.hpp -maxdepth 1 -print0 | xargs -0 scripts/autotemplate.sh
