name: template

on:
  push:
    paths:
      - src

jobs:
  template:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Delete live templates
      run: git diff --cached --name-only --diff-filter=D | grep "src/.*\.hpp$" | sed -e "s/src/templates/g" -e "s/hpp$/xml/g" | xargs rm -f

    - name: Delete renamed templates
      run: git diff --cached | grep "rename from src/.*\.hpp$" | sed -e "s/rename from //g" -e "s/src/templates/g" -e "s/hpp$/xml/g" | xargs rm -f

    - name: Generate live templates
      run: find src/*.hpp -maxdepth 1 -print0 | xargs -0 scripts/autotemplate.sh

    - uses: EndBug/add-and-commit@v7
      with:
        add: templates