name: template

on:
  push:
    paths:
      - 'src/**'

jobs:
  template:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Remove live templates
      run: rm -rf templates

    - name: Generate live templates
      run: find src/*.hpp -maxdepth 1 -print0 | xargs -0 scripts/autotemplate.sh

    - uses: EndBug/add-and-commit@v7
      with:
        add: templates